server:
  port: 6060
spring: 
  application:
    name: Attendance
  cloud:
    gcp:
      enabled: true
      storage:
        bucket: fisa_final_project
        project-id: woven-coral-441407-d3
        # credentials:
        #   location: ${GCP_KEY}
    config:
      enabled: false
  datasource:
    url: jdbc:mysql://mysql:3306/attendance
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: always
      table-prefix: BATCH_
    job:
      enabled: false
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: none    # JPA 테이블 자동 생성
    defer-datasource-initialization: true
aes:
  key: ${AES_KEY}
